clc;
clear;
data=importdata('data.txt');
time=0:0.02:0.02*(length(data)-1);
plot(time,data);
hold on;
setting=ones(1,length(data))*                 0.2                                                *36*60/0.055/3.14159;
plot(time,setting);
plot(time,setting,'-.');
hold off;