// Generated by gencpp from file shop_msgs/Pid.msg
// DO NOT EDIT!


#ifndef SHOP_MSGS_MESSAGE_PID_H
#define SHOP_MSGS_MESSAGE_PID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shop_msgs
{
template <class ContainerAllocator>
struct Pid_
{
  typedef Pid_<ContainerAllocator> Type;

  Pid_()
    : p(0.0)
    , i(0.0)
    , d(0.0)  {
    }
  Pid_(const ContainerAllocator& _alloc)
    : p(0.0)
    , i(0.0)
    , d(0.0)  {
  (void)_alloc;
    }



   typedef float _p_type;
  _p_type p;

   typedef float _i_type;
  _i_type i;

   typedef float _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::shop_msgs::Pid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shop_msgs::Pid_<ContainerAllocator> const> ConstPtr;

}; // struct Pid_

typedef ::shop_msgs::Pid_<std::allocator<void> > Pid;

typedef boost::shared_ptr< ::shop_msgs::Pid > PidPtr;
typedef boost::shared_ptr< ::shop_msgs::Pid const> PidConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shop_msgs::Pid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shop_msgs::Pid_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shop_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'shop_msgs': ['/home/nqq09/ShopRobot_ws/src/ShopRobot_ROS/shoprobot_base/shop_msgs/msgs'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shop_msgs::Pid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shop_msgs::Pid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shop_msgs::Pid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shop_msgs::Pid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shop_msgs::Pid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shop_msgs::Pid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shop_msgs::Pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cccd09188ee638c943ed6be95f1812c9";
  }

  static const char* value(const ::shop_msgs::Pid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcccd09188ee638c9ULL;
  static const uint64_t static_value2 = 0x43ed6be95f1812c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::shop_msgs::Pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shop_msgs/Pid";
  }

  static const char* value(const ::shop_msgs::Pid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shop_msgs::Pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 p\n\
float32 i\n\
float32 d\n\
\n\
";
  }

  static const char* value(const ::shop_msgs::Pid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shop_msgs::Pid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
      stream.next(m.i);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shop_msgs::Pid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shop_msgs::Pid_<ContainerAllocator>& v)
  {
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "i: ";
    Printer<float>::stream(s, indent + "  ", v.i);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHOP_MSGS_MESSAGE_PID_H
