// Generated by gencpp from file shop_msgs/LaserDistance.msg
// DO NOT EDIT!


#ifndef SHOP_MSGS_MESSAGE_LASERDISTANCE_H
#define SHOP_MSGS_MESSAGE_LASERDISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shop_msgs
{
template <class ContainerAllocator>
struct LaserDistance_
{
  typedef LaserDistance_<ContainerAllocator> Type;

  LaserDistance_()
    : laser1_distance(0.0)
    , laser2_distance(0.0)
    , laser3_distance(0.0)
    , laser4_distance(0.0)  {
    }
  LaserDistance_(const ContainerAllocator& _alloc)
    : laser1_distance(0.0)
    , laser2_distance(0.0)
    , laser3_distance(0.0)
    , laser4_distance(0.0)  {
  (void)_alloc;
    }



   typedef float _laser1_distance_type;
  _laser1_distance_type laser1_distance;

   typedef float _laser2_distance_type;
  _laser2_distance_type laser2_distance;

   typedef float _laser3_distance_type;
  _laser3_distance_type laser3_distance;

   typedef float _laser4_distance_type;
  _laser4_distance_type laser4_distance;





  typedef boost::shared_ptr< ::shop_msgs::LaserDistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shop_msgs::LaserDistance_<ContainerAllocator> const> ConstPtr;

}; // struct LaserDistance_

typedef ::shop_msgs::LaserDistance_<std::allocator<void> > LaserDistance;

typedef boost::shared_ptr< ::shop_msgs::LaserDistance > LaserDistancePtr;
typedef boost::shared_ptr< ::shop_msgs::LaserDistance const> LaserDistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shop_msgs::LaserDistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shop_msgs::LaserDistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shop_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'shop_msgs': ['/home/nqq09/ShopRobot_ws/src/ShopRobot_ROS/shoprobot_base/shop_msgs/msgs'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shop_msgs::LaserDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shop_msgs::LaserDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shop_msgs::LaserDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shop_msgs::LaserDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shop_msgs::LaserDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shop_msgs::LaserDistance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shop_msgs::LaserDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89f28b43382248c193db36c40531362e";
  }

  static const char* value(const ::shop_msgs::LaserDistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89f28b43382248c1ULL;
  static const uint64_t static_value2 = 0x93db36c40531362eULL;
};

template<class ContainerAllocator>
struct DataType< ::shop_msgs::LaserDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shop_msgs/LaserDistance";
  }

  static const char* value(const ::shop_msgs::LaserDistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shop_msgs::LaserDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 laser1_distance\n\
float32 laser2_distance\n\
float32 laser3_distance\n\
float32 laser4_distance\n\
";
  }

  static const char* value(const ::shop_msgs::LaserDistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shop_msgs::LaserDistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.laser1_distance);
      stream.next(m.laser2_distance);
      stream.next(m.laser3_distance);
      stream.next(m.laser4_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaserDistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shop_msgs::LaserDistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shop_msgs::LaserDistance_<ContainerAllocator>& v)
  {
    s << indent << "laser1_distance: ";
    Printer<float>::stream(s, indent + "  ", v.laser1_distance);
    s << indent << "laser2_distance: ";
    Printer<float>::stream(s, indent + "  ", v.laser2_distance);
    s << indent << "laser3_distance: ";
    Printer<float>::stream(s, indent + "  ", v.laser3_distance);
    s << indent << "laser4_distance: ";
    Printer<float>::stream(s, indent + "  ", v.laser4_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHOP_MSGS_MESSAGE_LASERDISTANCE_H
